version: "3.8"
services: 
  frontend:
    container_name: frontend
    platform: linux/amd64
    build: .
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
  nginx:
    container_name: nginx
    platform: linux/amd64
    build:
      context: ./nginx
    ports:
      - 80:80