version: "3.8"
services: 
  frontend:
    platform: linux/amd64
    container_name: frontend
    build: .
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 8080:80